apiVersion: v1
kind: Service
metadata:
  name: test-service2
  namespace : ngrok-ingress-controller
spec:
  selector:
    app: act3-kubernetes-test-app
  ports:
   - port: 80
     targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: act3-kubernetes-test-app
  namespace: ngrok-ingress-controller
spec:
  selector:
    matchLabels:
      app: act3-kubernetes-test-app
  replicas: 3
  template:
    metadata:
      labels:
        app: act3-kubernetes-test-app
    spec:
      containers:
      - name: backend
        image: act3-kubernetes2
        ports :
          - name: http
            containerPort: 80
        imagePullPolicy: IfNotPresent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ngrok-ingress
  namespace: ngrok-ingress-controller
spec:
  ingressClassName: ngrok
  rules:
    - host: bluebird-still-gladly.ngrok-free.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-ngrok-ingress
                port:
                  number: 80
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-system
data:
  cluster-name: act3-cluster